### ISSUE TITLE
Error when trying to run multiple Surround tasks simultaneously

### ISSUE THREAD

**Issue by anjsimmo** [a2i2/surround#230]
While waiting for a slow Surround task to complete, it would be useful for to be able to run a second Surround task in parellel (e.g. training models while waiting for a separate test dataset to download).

**Expected behaviour**
* It should be possible to run multiple tasks simultaneously, or the same task (with different inputs) in parrellel.
* It should always be safe to call `surround run` to get a list of tasks.

**Actual behaviour**
* If a Surround task is already running in the background, trying to run a second task (or even just `surround run` in order to get a list of tasks), will (sometimes) fail.

Example for MSR Surround project (with one Surround task already running in the background):
```
(surroundpy) asimmons@jagannath:~/mining-nlp-repositories$ surround run
Project tasks:
Traceback (most recent call last):
  File "/home/asimmons/mining-nlp-repositories/surroundpy/lib/python3.6/site-packages/doit/dependency.py", line 139, in __init__
    self._dbm = ddbm.open(self.name, 'c')
  File "/usr/lib/python3.6/dbm/__init__.py", line 94, in open
    return mod.open(file, flag, mode)
_gdbm.error: [Errno 11] Resource temporarily unavailable
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/asimmons/mining-nlp-repositories/surroundpy/lib/python3.6/site-packages/doit/doit_cmd.py", line 177, in run
    return command.parse_execute(args)
  File "/home/asimmons/mining-nlp-repositories/surroundpy/lib/python3.6/site-packages/doit/cmd_base.py", line 127, in parse_execute
    return self.execute(params, args)
  File "/home/asimmons/mining-nlp-repositories/surroundpy/lib/python3.6/site-packages/doit/cmd_base.py", line 406, in execute
    db_class, params['dep_file'], checker_cls)
  File "/home/asimmons/mining-nlp-repositories/surroundpy/lib/python3.6/site-packages/doit/dependency.py", line 475, in __init__
    self.backend = db_class(backend_name)
  File "/home/asimmons/mining-nlp-repositories/surroundpy/lib/python3.6/site-packages/doit/dependency.py", line 154, in __init__
    raise DatabaseException(message)
doit.dependency.DatabaseException: [Errno 11] Resource temporarily unavailable
```

**Cause**

Doit requires the `--backend sqlite3` flag to safely support concurrent access:
https://pydoit.org/cmd_run.html?highlight=sqlite3#db-backend

However, Surround doesn't provide a way for projects to enable this:
https://github.com/a2i2/surround/blob/v0.0.13/surround/cli.py#L289

```
run_args = [sys.executable, '-m', 'doit']
```

**Comment by ScottyB** [comment]
Hi Andrew, 
You can resolve this problem by adding `'backend':'sqlite3'` to the `DOIT_CONFIG` variable in the generated dodo.py file. I think it is important enough to add to the generated template though.
